# Anisotropic spherical DF with constant beta for power-law tracer in power-law potential
#
# f(E,L) = L^{-2*beta} * eta * epsilon^n
# where epsilon = -E, n = (gamma-2*beta)/(alpha-2) + beta - 3/2
#
# For rho_pot ~ r^{-alpha} (alpha > 2) and nu_tracer ~ r^{-gamma}
import numpy
from scipy import special

from ..potential import PowerSphericalPotential, evaluatePotentials
from ..potential.Potential import _evaluatePotentials
from ..util import conversion
from .constantbetadf import _constantbetadf
from .sphericaldf import _handle_rmin


class constantbetaPowerLawdf(_constantbetadf):
    """Class that implements the anisotropic spherical distribution function with constant :math:`\\beta` for a power-law tracer density :math:`\\nu(r) = \\nu_0\\,r^{-\\gamma}` in a power-law potential :math:`\\Phi(r) = -\\Psi_0\\,r^{2-\\alpha}` generated by :math:`\\rho(r) \\propto r^{-\\alpha}` with :math:`\\alpha > 2`, where :math:`\\Psi_0 = -\\Phi(1)` and :math:`\\nu_0 = \\nu(1)`.

    The distribution function is

    .. math::

        f(E,L) = L^{-2\\beta}\\,\\frac{\\nu_0\\,2^\\beta\\,\\Gamma(p+1)}{(2\\pi)^{3/2}\\,\\Gamma(1-\\beta)\\,\\Gamma(p+\\beta-\\tfrac{1}{2})\\,\\Psi_0^{p}}\\,\\mathcal{E}^{p+\\beta-3/2}

    where :math:`\\mathcal{E} = -E \\geq 0` is the relative energy and :math:`p = (\\gamma - 2\\beta)/(\\alpha - 2)`.
    """

    def __init__(
        self,
        pot=None,
        denspot=None,
        beta=0,
        rmax=1e4,
        rmin=None,
        ro=None,
        vo=None,
    ):
        """
        Initialize a constant-anisotropy power-law distribution function.

        Parameters
        ----------
        pot : PowerSphericalPotential
            Power-law potential with alpha > 2.
        denspot : PowerSphericalPotential, optional
            Power-law potential representing the tracer density. If None, self-consistent (tracer = potential-generating density).
        beta : float, optional
            Anisotropy parameter. Must be < 1. Default: 0.
        rmax : float or Quantity, optional
            Maximum radius for sampling. Default: 1e4.
        rmin : float or Quantity, optional
            Minimum radius. Auto-detected for divergent potentials if not specified.
        ro : float or Quantity, optional
            Distance scale for translation into internal units (default from configuration file).
        vo : float or Quantity, optional
            Velocity scale for translation into internal units (default from configuration file).

        Notes
        -----
        - 2025-03-27 - Written - Bovy (UofT)
        """
        assert isinstance(pot, PowerSphericalPotential), (
            "pot= must be potential.PowerSphericalPotential"
        )
        assert pot.alpha > 2.0, "pot.alpha must be > 2 for bound orbits"
        assert beta < 1.0, "beta must be < 1"
        self._alpha_pot = pot.alpha
        # Resolve tracer density
        if denspot is not None:
            assert isinstance(denspot, PowerSphericalPotential), (
                "denspot= must be potential.PowerSphericalPotential"
            )
            self._gamma = denspot.alpha
        else:
            self._gamma = self._alpha_pot
        assert self._gamma < 3.0, "gamma must be < 3 for finite enclosed mass"
        _constantbetadf.__init__(
            self, pot=pot, denspot=denspot, beta=beta, rmax=rmax, ro=ro, vo=vo
        )
        self._rmin = _handle_rmin(
            rmin,
            self._pot,
            self._denspot,
            self._scale,
            self._ro,
            "constantbetaPowerLawdf",
        )
        # Precompute normalization constants
        self._C = pot._amp / (self._alpha_pot - 2.0)
        denspot_use = (
            self._denspot if not isinstance(self._denspot, list) else self._denspot[0]
        )
        self._nu0 = denspot_use._amp * (3.0 - self._gamma) / (4.0 * numpy.pi)
        # Exponents
        self._p = (self._gamma - 2.0 * self._beta) / (self._alpha_pot - 2.0)
        self._n = self._p + self._beta - 1.5
        assert self._n > -1.0, (
            f"Energy exponent n={self._n:.3f} must be > -1 for the DF to be normalizable. "
            "Adjust gamma, alpha, or beta."
        )
        # eta = nu_0 * 2^beta * Gamma(p+1) / ((2*pi)^{3/2} * Gamma(1-beta) * Gamma(n+1) * C^p)
        self._fEnorm = (
            self._nu0
            * 2.0**self._beta
            * special.gamma(self._p + 1.0)
            / (
                (2.0 * numpy.pi) ** 1.5
                * special.gamma(1.0 - self._beta)
                * special.gamma(self._n + 1.0)
                * self._C**self._p
            )
        )
        self._potInf = evaluatePotentials(self._pot, self._rmax, 0, use_physical=False)

    def fE(self, E):
        """
        Calculate the energy portion of the constant-beta power-law distribution function.

        Parameters
        ----------
        E : float, numpy.ndarray, or Quantity
            The energy.

        Returns
        -------
        numpy.ndarray
            The value of the energy portion of the DF.

        Notes
        -----
        - 2025-03-27 - Written - Bovy (UofT)
        """
        Eint = numpy.atleast_1d(conversion.parse_energy(E, vo=self._vo))
        eps = -Eint
        out = numpy.zeros_like(eps)
        valid = eps > 0.0
        out[valid] = self._fEnorm * eps[valid] ** self._n
        if hasattr(E, "shape"):
            return out.reshape(E.shape)
        return out[0]

    def _vmax_at_r(self, pot, r, **kwargs):
        # For alpha > 2, Phi(inf) = 0, so v_esc = sqrt(-2*Phi(r))
        return numpy.sqrt(-2.0 * _evaluatePotentials(self._pot, r, 0.0))

    def _icmf(self, ms):
        """Analytic inverse cumulative mass function for the tracer density.
        The argument ms is normalized mass fraction [0,1]."""
        rmin_g = self._rmin ** (3.0 - self._gamma)
        rmax_g = self._rmax ** (3.0 - self._gamma)
        return (ms * (rmax_g - rmin_g) + rmin_g) ** (1.0 / (3.0 - self._gamma))
