# Isotropic spherical DF for power-law tracer density in a power-law potential
#
# f(epsilon) = eta * epsilon^n
# where epsilon = -E, n = gamma/(alpha-2) - 3/2
#
# For rho_pot ~ r^{-alpha} (alpha > 2) and nu_tracer ~ r^{-gamma}
import numpy
from scipy import special

from ..potential import PowerSphericalPotential, evaluatePotentials
from ..potential.Potential import _evaluatePotentials
from ..util import conversion
from .sphericaldf import _handle_rmin, isotropicsphericaldf


class isotropicPowerLawdf(isotropicsphericaldf):
    """Class that implements the isotropic spherical distribution function for a power-law tracer density :math:`\\nu(r) = \\nu_0\\,r^{-\\gamma}` in a power-law potential :math:`\\Phi(r) = -\\Psi_0\\,r^{2-\\alpha}` generated by :math:`\\rho(r) \\propto r^{-\\alpha}` with :math:`\\alpha > 2`, where :math:`\\Psi_0 = -\\Phi(1)` and :math:`\\nu_0 = \\nu(1)`.

    The distribution function is

    .. math::

        f(\\mathcal{E}) = \\frac{\\nu_0\\,\\Gamma\\!\\left(\\frac{\\gamma}{\\alpha-2}+1\\right)}{2\\sqrt{2}\\,\\pi^{3/2}\\,\\Gamma\\!\\left(\\frac{\\gamma}{\\alpha-2}-\\frac{1}{2}\\right)\\,\\Psi_0^{\\gamma/(\\alpha-2)}}\\,\\mathcal{E}^{\\gamma/(\\alpha-2) - 3/2}

    where :math:`\\mathcal{E} = -E \\geq 0` is the relative energy.
    """

    def __init__(
        self, pot=None, denspot=None, gamma=None, rmax=1e4, rmin=None, ro=None, vo=None
    ):
        """
        Initialize an isotropic power-law distribution function.

        Parameters
        ----------
        pot : PowerSphericalPotential
            Power-law potential with alpha > 2.
        denspot : PowerSphericalPotential, optional
            Power-law potential representing the tracer density. If None, uses gamma or self-consistent (gamma=alpha).
        gamma : float, optional
            Power-law exponent of the tracer density (nu ~ r^{-gamma}). Ignored if denspot is given.
        rmax : float or Quantity, optional
            Maximum radius for sampling (required because the total mass is infinite). Default: 1e4.
        rmin : float or Quantity, optional
            Minimum radius. Auto-detected for divergent potentials if not specified.
        ro : float or Quantity, optional
            Distance scale for translation into internal units (default from configuration file).
        vo : float or Quantity, optional
            Velocity scale for translation into internal units (default from configuration file).

        Notes
        -----
        - 2025-03-27 - Written - Bovy (UofT)
        """
        assert isinstance(pot, PowerSphericalPotential), (
            "pot= must be potential.PowerSphericalPotential"
        )
        assert pot.alpha > 2.0, "pot.alpha must be > 2 for bound orbits"
        self._alpha_pot = pot.alpha
        # Resolve tracer density
        if denspot is not None:
            assert isinstance(denspot, PowerSphericalPotential), (
                "denspot= must be potential.PowerSphericalPotential"
            )
            self._gamma = denspot.alpha
        elif gamma is not None:
            self._gamma = gamma
        else:
            self._gamma = self._alpha_pot
        assert self._gamma > (self._alpha_pot - 2.0) / 2.0, (
            f"gamma={self._gamma} must be > (alpha-2)/2={(self._alpha_pot - 2.0) / 2.0} "
            "for the DF to be normalizable"
        )
        assert self._gamma < 3.0, "gamma must be < 3 for finite enclosed mass"
        # Build denspot if only gamma was given
        if denspot is None and gamma is not None:
            denspot = PowerSphericalPotential(amp=pot._amp, alpha=gamma)
        isotropicsphericaldf.__init__(
            self, pot=pot, denspot=denspot, rmax=rmax, ro=ro, vo=vo
        )
        self._rmin = _handle_rmin(
            rmin, self._pot, self._denspot, self._scale, self._ro, "isotropicPowerLawdf"
        )
        # Precompute normalization constants
        # Psi(r) = -Phi(r) = pot._amp / (alpha-2) * r^{2-alpha}
        # C = Psi(1) = pot._amp / (alpha-2)
        self._C = pot._amp / (self._alpha_pot - 2.0)
        # nu(1) = denspot density at r=1; _dens returns without _amp
        denspot_use = (
            self._denspot if not isinstance(self._denspot, list) else self._denspot[0]
        )
        self._nu0 = denspot_use._amp * (3.0 - self._gamma) / (4.0 * numpy.pi)
        # Exponents
        self._s = self._gamma / (self._alpha_pot - 2.0)
        self._n = self._s - 1.5
        # eta = nu_0 * Gamma(s+1) / (2*sqrt(2) * pi^{3/2} * Gamma(s-1/2) * C^s)
        self._fEnorm = (
            self._nu0
            * special.gamma(self._s + 1.0)
            / (
                2.0
                * numpy.sqrt(2.0)
                * numpy.pi**1.5
                * special.gamma(self._s - 0.5)
                * self._C**self._s
            )
        )
        self._potInf = evaluatePotentials(self._pot, self._rmax, 0, use_physical=False)

    def fE(self, E):
        """
        Calculate the energy portion of the isotropic power-law distribution function.

        Parameters
        ----------
        E : float, numpy.ndarray, or Quantity
            The energy.

        Returns
        -------
        numpy.ndarray
            The value of the DF.

        Notes
        -----
        - 2025-03-27 - Written - Bovy (UofT)
        """
        Eint = numpy.atleast_1d(conversion.parse_energy(E, vo=self._vo))
        eps = -Eint
        out = numpy.zeros_like(eps)
        valid = eps > 0.0
        out[valid] = self._fEnorm * eps[valid] ** self._n
        if hasattr(E, "shape"):
            return out.reshape(E.shape)
        return out[0]

    def _vmax_at_r(self, pot, r, **kwargs):
        # For alpha > 2, Phi(inf) = 0, so v_esc = sqrt(-2*Phi(r))
        return numpy.sqrt(-2.0 * _evaluatePotentials(self._pot, r, 0.0))

    def _icmf(self, ms):
        """Analytic inverse cumulative mass function for the tracer density.
        The argument ms is normalized mass fraction [0,1]."""
        rmin_g = self._rmin ** (3.0 - self._gamma)
        rmax_g = self._rmax ** (3.0 - self._gamma)
        return (ms * (rmax_g - rmin_g) + rmin_g) ** (1.0 / (3.0 - self._gamma))
