# Osipkov-Merritt anisotropic spherical DF for power-law tracer in power-law potential
#
# f(Q) = A1 * Q^n1 + A2 * Q^n2
# where Q = epsilon - L^2/(2*ra^2), and the two terms come from the
# augmented density nu(r)*(1 + r^2/ra^2) = nu_0*r^{-gamma} + nu_0/ra^2 * r^{-gamma+2}
#
# For rho_pot ~ r^{-alpha} (alpha > 2) and nu_tracer ~ r^{-gamma}
import numpy
from scipy import special

from ..potential import PowerSphericalPotential, evaluatePotentials
from ..potential.Potential import _evaluatePotentials
from ..util import conversion
from .osipkovmerrittdf import _osipkovmerrittdf
from .sphericaldf import _handle_rmin


class osipkovmerrittPowerLawdf(_osipkovmerrittdf):
    """Class that implements the Osipkov-Merritt anisotropic spherical distribution function for a power-law tracer density :math:`\\nu(r) = \\nu_0\\,r^{-\\gamma}` in a power-law potential :math:`\\Phi(r) = -\\Psi_0\\,r^{2-\\alpha}` generated by :math:`\\rho(r) \\propto r^{-\\alpha}` with :math:`\\alpha > 2`, where :math:`\\Psi_0 = -\\Phi(1)` and :math:`\\nu_0 = \\nu(1)`.

    The anisotropy profile is

    .. math::

        \\beta(r) = \\frac{1}{1+r_a^2/r^2}

    with :math:`r_a` the anisotropy radius. The distribution function is

    .. math::

        f(Q) = \\frac{\\nu_0}{2\\sqrt{2}\\,\\pi^{3/2}}\\left[\\frac{\\Gamma(s_1+1)}{\\Gamma(s_1-\\tfrac{1}{2})\\,\\Psi_0^{s_1}}\\,Q^{s_1-3/2} + \\frac{\\Gamma(s_2+1)}{\\Gamma(s_2-\\tfrac{1}{2})\\,r_a^2\\,\\Psi_0^{s_2}}\\,Q^{s_2-3/2}\\right]

    where :math:`Q = -E - L^2/(2r_a^2) \\geq 0`, :math:`s_1 = \\gamma/(\\alpha-2)`, and :math:`s_2 = (\\gamma-2)/(\\alpha-2)`.
    """

    def __init__(
        self,
        pot=None,
        denspot=None,
        ra=1.4,
        gamma=None,
        rmax=1e4,
        rmin=None,
        ro=None,
        vo=None,
    ):
        """
        Initialize an Osipkov-Merritt power-law distribution function.

        Parameters
        ----------
        pot : PowerSphericalPotential
            Power-law potential with alpha > 2.
        denspot : PowerSphericalPotential, optional
            Power-law potential representing the tracer density. If None, uses gamma or self-consistent (gamma=alpha).
        ra : float or Quantity, optional
            Anisotropy radius. Default: 1.4.
        gamma : float, optional
            Power-law exponent of the tracer density (nu ~ r^{-gamma}). Ignored if denspot is given.
        rmax : float or Quantity, optional
            Maximum radius for sampling. Default: 1e4.
        rmin : float or Quantity, optional
            Minimum radius. Auto-detected for divergent potentials if not specified.
        ro : float or Quantity, optional
            Distance scale for translation into internal units (default from configuration file).
        vo : float or Quantity, optional
            Velocity scale for translation into internal units (default from configuration file).

        Notes
        -----
        - 2025-03-27 - Written - Bovy (UofT)
        """
        assert isinstance(pot, PowerSphericalPotential), (
            "pot= must be potential.PowerSphericalPotential"
        )
        assert pot.alpha > 2.0, "pot.alpha must be > 2 for bound orbits"
        self._alpha_pot = pot.alpha
        # Resolve tracer density
        if denspot is not None:
            assert isinstance(denspot, PowerSphericalPotential), (
                "denspot= must be potential.PowerSphericalPotential"
            )
            self._gamma = denspot.alpha
        elif gamma is not None:
            self._gamma = gamma
        else:
            self._gamma = self._alpha_pot
        assert self._gamma > self._alpha_pot / 2.0, (
            f"gamma={self._gamma} must be > alpha/2={self._alpha_pot / 2.0} "
            "for the Osipkov-Merritt DF to be normalizable"
        )
        assert self._gamma < 3.0, "gamma must be < 3 for finite enclosed mass"
        # Build denspot if only gamma was given
        if denspot is None and gamma is not None:
            denspot = PowerSphericalPotential(amp=pot._amp, alpha=gamma)
        _osipkovmerrittdf.__init__(
            self, pot=pot, denspot=denspot, ra=ra, rmax=rmax, ro=ro, vo=vo
        )
        self._rmin = _handle_rmin(
            rmin,
            self._pot,
            self._denspot,
            self._scale,
            self._ro,
            "osipkovmerrittPowerLawdf",
        )
        # Precompute normalization constants
        self._C = pot._amp / (self._alpha_pot - 2.0)
        denspot_use = (
            self._denspot if not isinstance(self._denspot, list) else self._denspot[0]
        )
        self._nu0 = denspot_use._amp * (3.0 - self._gamma) / (4.0 * numpy.pi)
        # Exponents for the two terms: nu_aug = nu_0*r^{-gamma} + nu_0/ra^2 * r^{-gamma+2}
        self._s1 = self._gamma / (self._alpha_pot - 2.0)
        self._s2 = (self._gamma - 2.0) / (self._alpha_pot - 2.0)
        self._n1 = self._s1 - 1.5
        self._n2 = self._s2 - 1.5
        # Eddington normalization for each power-law term of the augmented density
        edd_norm = 2.0 * numpy.sqrt(2.0) * numpy.pi**1.5
        self._A1 = (
            self._nu0
            / self._C**self._s1
            * special.gamma(self._s1 + 1.0)
            / (edd_norm * special.gamma(self._s1 - 0.5))
        )
        self._A2 = (
            self._nu0
            / (self._ra2 * self._C**self._s2)
            * special.gamma(self._s2 + 1.0)
            / (edd_norm * special.gamma(self._s2 - 0.5))
        )
        self._potInf = evaluatePotentials(self._pot, self._rmax, 0, use_physical=False)

    def fQ(self, Q):
        """
        Calculate the f(Q) portion of the Osipkov-Merritt power-law distribution function.

        Parameters
        ----------
        Q : float, numpy.ndarray, or Quantity
            The Osipkov-Merritt 'energy' Q = -E - L^2/(2*ra^2).

        Returns
        -------
        numpy.ndarray
            The value of f(Q).

        Notes
        -----
        - 2025-03-27 - Written - Bovy (UofT)
        """
        Qint = numpy.atleast_1d(conversion.parse_energy(Q, vo=self._vo))
        out = numpy.zeros_like(Qint)
        valid = Qint > 0.0
        out[valid] = (
            self._A1 * Qint[valid] ** self._n1 + self._A2 * Qint[valid] ** self._n2
        )
        if hasattr(Q, "shape"):
            return out.reshape(Q.shape)
        return out[0]

    def _vmax_at_r(self, pot, r, **kwargs):
        # For alpha > 2, Phi(inf) = 0, so v_esc = sqrt(-2*Phi(r))
        return numpy.sqrt(-2.0 * _evaluatePotentials(self._pot, r, 0.0))

    def _icmf(self, ms):
        """Analytic inverse cumulative mass function for the tracer density.
        The argument ms is normalized mass fraction [0,1]."""
        rmin_g = self._rmin ** (3.0 - self._gamma)
        rmax_g = self._rmax ** (3.0 - self._gamma)
        return (ms * (rmax_g - rmin_g) + rmin_g) ** (1.0 / (3.0 - self._gamma))
